# Generated by Django 3.2.16 on 2022-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reporter', models.CharField(max_length=50)),
                ('assignee', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
    ]
