# Generated by Django 3.0 on 2022-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_r',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='sprint',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
