version: 3.10.2
services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
  web:
    build: .
    command: >-
      sh -c "python /project/manage.py migrate && python /project/manage.py
      runserver 0.0.0.0:8000"
    volumes:
      - '.:/project'
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  postgres_data: null